#!/bin/bash

drupclean() {
  read -p "Ok I found out we are n a Drupal root. Are you sure you want to wipe all cache tables in database?" YN
  if [ "$YN" == "y" ]] ; then
    echo "SHOW TABLES LIKE 'cache%'" | $(drush sql-connect) | tail -n +2 | xargs -L1 -I% echo "TRUNCATE TABLE %;" | $(drush sql-connect) -v
  else
    echo "Ok. I broke up and quit."
    exit 0
}

f() {
  (
    while [[ "$PWD" != / ]] ; do 
      [[ -f "index.php" ]] && [[ "$(cat index.php)" == *"Drupal"* ]] return 0 # && exit 0
      cd ..
    done
    return 1
    )
}

if f ; then 
 drupclean
else
 echo "Is this a Drupal project directory?"
fi
